[package]
name = "amalthea-flight-code"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = "^0.7.3"
cortex-m-rt = "^0.7.3"
embedded-hal = "0.2.4"
panic-halt = "^0.2.0"
multi-mission-library-rs = "0.1.2"

[dependencies.stm32f4xx-hal]
features = ["stm32f411"]
version = "0.20.0"